### ISSUE TITLE
Corporate Public Page functionality on the site

### ISSUE THREAD

**Issue by SvitlanaShepitsena** [SvitlanaShepitsena/svet-newspaper-material#107]

**Comment by ChicagoBusinessIntelligence1** [comment]
With corporate logo upload functionality.

**Comment by ChicagoBusinessIntelligence1** [comment]
Advantages to corporate users:
1. Incoming link to their site (if they have a site)
2. Business Page on Svet Media Group site if they are not presented in web.
3. Social Hub aggregation
4. Banner order ad functionality with free try out for people who registered to connection event via site
